# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 307679f0fb11630b7784b0c9d48209566d80195fcd02f9838fe419b09566052faf642484d5bfcbd03f88ec8ae02b45585bf71b331d360f902b152dffa5e7fbd2

test:
  secret_key_base: fe261fb1f2f76f22472122dc2acea3ff75b863d8bbd8171f51fc860b9391755817a563e036044f9257285c2098fc3e76cdfc092f381babe01b5914f67c4ec870

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
